package gameOfLife

import input.KeyHandler
import input.MouseHandler
import input.UserControllable
import org.lwjgl.glfw.GLFW
import java.util.*

class GameOfLife(pattern : Pattern) : UserControllable {
    private var alivePoints: HashSet<Point> = pattern.read()
    private var generationsPer60Frames = 1
    private var paused = true

    // Generated by ChatGPT
    fun nextGeneration() {
        if (paused) return

        val newAlivePoints = HashSet<Point>()
        val pointsToCheck = HashSet<Point>()

        // Collect points to check (alive points and their neighbors)
        alivePoints.forEach { point ->
            pointsToCheck.add(point)
            pointsToCheck.addAll(getNeighbours(point))
        }

        // Apply Game of Life rules
        pointsToCheck.forEach { point ->
            val aliveNeighbors = getNeighbours(point).count { it in alivePoints }
            if (point in alivePoints) {
                if (aliveNeighbors == 2 || aliveNeighbors == 3) {
                    newAlivePoints.add(point)
                }
            } else {
                if (aliveNeighbors == 3) {
                    newAlivePoints.add(point)
                }
            }
        }

        // Update alive points
        alivePoints = newAlivePoints
    }

    private fun getNeighbours(point: Point): List<Point> {
        val (x, y) = point
        return listOf(
            Point(x - 1, y - 1), Point(x, y - 1), Point(x + 1, y - 1),
            Point(x - 1, y), /*       point          */ Point(x + 1, y),
            Point(x - 1, y + 1), Point(x, y + 1), Point(x + 1, y + 1)
        )
    }

    override fun applyChanges(keyHandler: KeyHandler, mouseHandler: MouseHandler) {
        if (keyHandler.isKeyJustPressed(GLFW.GLFW_KEY_UP)) generationsPer60Frames *= 2
        if (keyHandler.isKeyJustPressed(GLFW.GLFW_KEY_DOWN)) generationsPer60Frames /= 2
        if (generationsPer60Frames < 1) generationsPer60Frames = 1
        if (generationsPer60Frames >= 60) generationsPer60Frames = 60

        if (keyHandler.isKeyJustPressed(GLFW.GLFW_KEY_SPACE)) paused = !paused
    }

    fun getAlivePoints(): HashSet<Point> = alivePoints
    fun getGenerationsPer60Frames(): Int = generationsPer60Frames
}
